### ISSUE TITLE
TXT record parsing fails when data length is 0

### ISSUE THREAD

**Issue by darmbrust** [fflewddur/hola#14]
Exception in thread "Thread-2" java.nio.BufferUnderflowException
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:178)
	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:762)
	at net.straylightlabs.hola.dns.Record.readLabel(Record.java:122)
	at net.straylightlabs.hola.dns.Record.readStringsFromBuffer(Record.java:137)
	at net.straylightlabs.hola.dns.TxtRecord.<init>(TxtRecord.java:39)
	at net.straylightlabs.hola.dns.Record.fromBuffer(Record.java:74)
	at net.straylightlabs.hola.dns.Response.parseRecords(Response.java:77)
	at net.straylightlabs.hola.dns.Response.createFrom(Response.java:45)
	at net.straylightlabs.hola.sd.Query.collectResponses(Query.java:218)

**Comment by darmbrust** [comment]
![screenshot17](https://user-images.githubusercontent.com/5016252/79918349-d7da8200-83f1-11ea-817f-c41bb0f31297.png)

Wireshark capture of the response in question

**Comment by darmbrust** [comment]
fixed in the above commit on my fork, if you need a release, see https://github.com/Sagebits/hola/releases/tag/v0.2.4-sagebits

also published to maven central as 
```
<dependency>
	<groupId>net.sagebits</groupId>
	<artifactId>hola</artifactId>
	<version>0.2.4-sagebits</version>
</dependency>
```
